CREATE SEQUENCE empresa_id_seq START 1;

CREATE OR REPLACE FUNCTION add_empresa(nome_empresa VARCHAR(500))
    RETURNS INT AS
$$
DECLARE
    id_seq_em INT;
BEGIN
    id_seq_em = nextval('empresa_id_seq');

    INSERT INTO empresa (id, nome, ativo)
    VALUES(id_seq_em, nome_empresa, true);

    RETURN id_seq_em;
END;
$$ LANGUAGE plpgsql;

SELECT add_empresa('Afluente T');

select * from empresa;

SELECT add_empresa('Simpar');
SELECT add_empresa('Cury');
SELECT add_empresa('Plano & Plano');
SELECT add_empresa('Petz');
SELECT add_empresa('Pague Menos');
SELECT add_empresa('Lavvi Incorporadora');
SELECT add_empresa('Quero-Quero');
SELECT add_empresa('d1000');
SELECT add_empresa('Grupo Soma');
SELECT add_empresa('Riva 9');
SELECT add_empresa('Ambipar');
SELECT add_empresa('Allpark');
SELECT add_empresa('Mitre Realty');
SELECT add_empresa('Moura Dubeux');
SELECT add_empresa('Bardella');
SELECT add_empresa('UPS');
SELECT add_empresa('Lockheed');
SELECT add_empresa('Johnson');
SELECT add_empresa('Fedex Corp');
SELECT add_empresa('Exxon Mobile');
SELECT add_empresa('Caterpillar');
SELECT add_empresa('Bristolmyers');
SELECT add_empresa('Boeing');
SELECT add_empresa('Arcelor');
SELECT add_empresa('American Express');
SELECT add_empresa('Abbott Laboratories');
SELECT add_empresa('Santos - Brasil');
SELECT add_empresa('Randon Part');
SELECT add_empresa('Engie');
SELECT add_empresa('MMX Mineração');
SELECT add_empresa('Lupatech');
SELECT add_empresa('Inepar');
SELECT add_empresa('Ger Paranapanema');
SELECT add_empresa('Fras-Le');
SELECT add_empresa('Afluente T');
SELECT add_empresa('Schulz');
SELECT add_empresa('Suzano Holding');
SELECT add_empresa('Taurus Armas');
SELECT add_empresa('Tecnisa');
SELECT add_empresa('Unipar');
SELECT add_empresa('Whirpool');
SELECT add_empresa('Whirlpool');
SELECT add_empresa('Ourofino S/A');
SELECT add_empresa('GOL');
SELECT add_empresa('Eternit');
SELECT add_empresa('Valid');
SELECT add_empresa('Triunfo Part');
SELECT add_empresa('PBG');
SELECT add_empresa('Marcopolo');
SELECT add_empresa('Cosan Log');
SELECT add_empresa('Aço Altona');
SELECT add_empresa('Eneva');
SELECT add_empresa('Banco Pan');
SELECT add_empresa('Weg');
SELECT add_empresa('ViaVarejo');
SELECT add_empresa('RUMO LOG');
SELECT add_empresa('Vale');
SELECT add_empresa('Usiminas');
SELECT add_empresa('Santos Brasil Participações');
SELECT add_empresa('Invepar');
SELECT add_empresa('Contax');
SELECT add_empresa('Celulose Irani');
SELECT add_empresa('CCR');
SELECT add_empresa('Cedro');
SELECT add_empresa('Netflix');
SELECT add_empresa('Nike');
SELECT add_empresa('MC Donald''s');
SELECT add_empresa('Home Depot');
SELECT add_empresa('Ford Motors');
SELECT add_empresa('Comcast');
SELECT add_empresa('Amazon');
SELECT add_empresa('Rodobens');
SELECT add_empresa('Saraiva Livr');
SELECT add_empresa('Rossi Resid');
SELECT add_empresa('Mundial');
SELECT add_empresa('Metal Leve');
SELECT add_empresa('Karsten');
SELECT add_empresa('Iochpe-Maxion');
SELECT add_empresa('Grendene');
SELECT add_empresa('Locamerica');
SELECT add_empresa('C&A');
SELECT add_empresa('Le Lis Blanc');
SELECT add_empresa('Grazziotin');
SELECT add_empresa('Estrela');
SELECT add_empresa('Direcional');
SELECT add_empresa('Coteminas');
SELECT add_empresa('Anima');
SELECT add_empresa('Even');
SELECT add_empresa('Marisa');
SELECT add_empresa('Movida');
SELECT add_empresa('JHSF');
SELECT add_empresa('Helbor');
SELECT add_empresa('PDG Realty');
SELECT add_empresa('Arezzo');
SELECT add_empresa('Ez Tec');
SELECT add_empresa('Cia Hering');
SELECT add_empresa('Alpargatas');
SELECT add_empresa('Smiles');
SELECT add_empresa('Localiza');
SELECT add_empresa('MRV Engenharia');
SELECT add_empresa('Magazine Luiza');
SELECT add_empresa('Lojas Renner');
SELECT add_empresa('Cogna');
SELECT add_empresa('Whirlpool');
SELECT add_empresa('Whirpool');
SELECT add_empresa('Via Varejo');
SELECT add_empresa('Tecnisa');
SELECT add_empresa('Starbuc');
SELECT add_empresa('Ser Educacional');
SELECT add_empresa('Saraiva livr');
SELECT add_empresa('Lojas Americanas');
SELECT add_empresa('Hoteis Othon');
SELECT add_empresa('Gafisa');
SELECT add_empresa('YDUQS');
SELECT add_empresa('Cyrela Realty');
SELECT add_empresa('CVC');
SELECT add_empresa('Walmart');
SELECT add_empresa('Starbucks');
SELECT add_empresa('Procter Gamble');
SELECT add_empresa('Pepsico Inc');
SELECT add_empresa('Colgate');
SELECT add_empresa('Coca-Cola');
SELECT add_empresa('Avon');
SELECT add_empresa('São Martinho');
SELECT add_empresa('MDiasBranco');
SELECT add_empresa('CAMIL');
SELECT add_empresa('Brasilagro');
SELECT add_empresa('Biosev');
SELECT add_empresa('Minerva');
SELECT add_empresa('Vivara');
SELECT add_empresa('Carrefour');
SELECT add_empresa('Pão de Açúcar');
SELECT add_empresa('Natura');
SELECT add_empresa('Marfrig');
SELECT add_empresa('JBS');
SELECT add_empresa('Proctor Gamb');
SELECT add_empresa('BRF');
SELECT add_empresa('BRB Banco');
SELECT add_empresa('Battistella');
SELECT add_empresa('Banpara');
SELECT add_empresa('Wells Fargo');
SELECT add_empresa('Visa');
SELECT add_empresa('Morgan Stanley');
SELECT add_empresa('Mastercard');
SELECT add_empresa('JPMorgan');
SELECT add_empresa('Honeywell');
SELECT add_empresa('GE');
SELECT add_empresa('Goldman Sachs');
SELECT add_empresa('Citigroup');
SELECT add_empresa('Bank America');
SELECT add_empresa('Sao Carlos');
SELECT add_empresa('LPS Brasil');
SELECT add_empresa('BMG');
SELECT add_empresa('Gradiente');
SELECT add_empresa('General Shopping');
SELECT add_empresa('Porto Seguro');
SELECT add_empresa('CSU CardSyst');
SELECT add_empresa('Brasil Brokers');
SELECT add_empresa('BR Properties');
SELECT add_empresa('Banrisul');
SELECT add_empresa('Banco Inter');
SELECT add_empresa('Santander BR');
SELECT add_empresa('Multiplan');
SELECT add_empresa('Itaú Unibanco');
SELECT add_empresa('Aliansce Sonae');
SELECT add_empresa('Banco Mercantil de Investimentos');
SELECT add_empresa('Mercantil do Brasil Financeira');
SELECT add_empresa('Log');
SELECT add_empresa('Itaúsa');
SELECT add_empresa('IRB Brasil RE');
SELECT add_empresa('Iguatemi');
SELECT add_empresa('Bradesco');
SELECT add_empresa('brMalls');
SELECT add_empresa('Alper');
SELECT add_empresa('BB Seguridade');
SELECT add_empresa('Banco Pan');
SELECT add_empresa('Banco do Brasil');
SELECT add_empresa('American Expre');
SELECT add_empresa('Celul Irani');
SELECT add_empresa('Freeport');
SELECT add_empresa('Paranapanema');
SELECT add_empresa('Ferbasa');
SELECT add_empresa('Eucatex');
SELECT add_empresa('Suzano Papel');
SELECT add_empresa('Klabin S/A');
SELECT add_empresa('Vale');
SELECT add_empresa('Unipar');
SELECT add_empresa('Suzano Holding');
SELECT add_empresa('MMX Mineração');
SELECT add_empresa('Gerdau');
SELECT add_empresa('CSN');
SELECT add_empresa('Celulose Irani');
SELECT add_empresa('Braskem');
SELECT add_empresa('Bradespar');
SELECT add_empresa('Arcel');
SELECT add_empresa('Zoetis Inc');
SELECT add_empresa('Zionsbancorp');
SELECT add_empresa('Zimmer Biome');
SELECT add_empresa('Yum Brands');
SELECT add_empresa('Dentsply Sir');
SELECT add_empresa('Xylem Inc');
SELECT add_empresa('Xilinx Inc');
SELECT add_empresa('Xcel Energy');
SELECT add_empresa('Westernunion');
SELECT add_empresa('Walgreens');
SELECT add_empresa('Waters Co');
SELECT add_empresa('Western Bcor');
SELECT add_empresa('Wynn Resorts');
SELECT add_empresa('Weyerhaeuser');
SELECT add_empresa('Westrock Co');
SELECT add_empresa('Waste Manag');
SELECT add_empresa('Williams Cos');
SELECT add_empresa('Willis Tower');
SELECT add_empresa('Whirlpool Co');
SELECT add_empresa('Welltower In');
SELECT add_empresa('Wec Energy G');
SELECT add_empresa('Western Dig');
SELECT add_empresa('Workday Inc');
SELECT add_empresa('Wabtec Corp');
SELECT add_empresa('Vertex Pharm');
SELECT add_empresa('Verisign Inc');
SELECT add_empresa('Valley Ntion');
SELECT add_empresa('Valero Ener');
SELECT add_empresa('Vf Corp');
SELECT add_empresa('Ventas Inc');
SELECT add_empresa('Verisk Analy');
SELECT add_empresa('Vornado Real');
SELECT add_empresa('Vulcan Mater');
SELECT add_empresa('Varian Med');
SELECT add_empresa('Us Steel');
SELECT add_empresa('Us Bancorp');
SELECT add_empresa('Unionpacific');
SELECT add_empresa('Unitedhealth');
SELECT add_empresa('Unilever');
SELECT add_empresa('Ubs Group');
SELECT add_empresa('United Renta');
SELECT add_empresa('Unum Group');
SELECT add_empresa('Ulta Beauty');
SELECT add_empresa('Universal He');
SELECT add_empresa('Udr Inc');
SELECT add_empresa('Uber Tech In');
SELECT add_empresa('United Airli');
SELECT add_empresa('Under Armour');
SELECT add_empresa('Terniumsa');
SELECT add_empresa('Twitter');
SELECT add_empresa('Tyson Foods');
SELECT add_empresa('Schlumberger');
SELECT add_empresa('Halliburton');
SELECT add_empresa('Cophilli');
SELECT add_empresa('Chevron');
SELECT add_empresa('PETRORIO');
SELECT add_empresa('OSX Brasil');
SELECT add_empresa('Dommo');
SELECT add_empresa('Pet Manguinhos');
SELECT add_empresa('Ultrapar');
SELECT add_empresa('Petrobras');
SELECT add_empresa('Petrobras Distribuidora');
SELECT add_empresa('Exxon Mob');
SELECT add_empresa('Enauta Part');
SELECT add_empresa('Instituto Hermes Pardini SA');
SELECT add_empresa('Biomm');
SELECT add_empresa('Baumer');
SELECT add_empresa('Pfizer');
SELECT add_empresa('Merck');
SELECT add_empresa('Biotoscana');
SELECT add_empresa('Dimed');
SELECT add_empresa('Alliar');
SELECT add_empresa('OdontoPrev');
SELECT add_empresa('RD');
SELECT add_empresa('Qualicorp');
SELECT add_empresa('Ourofino S/A');
SELECT add_empresa('Johns');
SELECT add_empresa('Hypera Pharma');
SELECT add_empresa('Fleury');
SELECT add_empresa('Bristolmye');
SELECT add_empresa('Abbott Laboratori');
SELECT add_empresa('Locaweb');
SELECT add_empresa('Totvs');
SELECT add_empresa('Xerox');
SELECT add_empresa('Qualcomm');
SELECT add_empresa('Oracle');
SELECT add_empresa('Microsoft');
SELECT add_empresa('IBM');
SELECT add_empresa('Intel');
SELECT add_empresa('HP Company');
SELECT add_empresa('eBay');
SELECT add_empresa('Cisco');
SELECT add_empresa('Att Inc');
SELECT add_empresa('Apple');
SELECT add_empresa('Linx');
SELECT add_empresa('Positivo Inf');
SELECT add_empresa('Ebay');
SELECT add_empresa('Verizon');
SELECT add_empresa('OI');
SELECT add_empresa('Tim Participações');
SELECT add_empresa('Telefônica Brasil S.A');
SELECT add_empresa('Telebras');
SELECT add_empresa('Att Inc');
SELECT add_empresa('Celpe');
SELECT add_empresa('CEEE-D');
SELECT add_empresa('Ceee-gt');
SELECT add_empresa('Casan');
SELECT add_empresa('CEG');
SELECT add_empresa('CEB');
SELECT add_empresa('Renova');
SELECT add_empresa('Coelce');
SELECT add_empresa('Celesc');
SELECT add_empresa('Alupar Investimento');
SELECT add_empresa('Sanepar');
SELECT add_empresa('CPFL Renovav');
SELECT add_empresa('Copel');
SELECT add_empresa('CPFL Energia');
SELECT add_empresa('Comgás');
SELECT add_empresa('AES Tietê');
SELECT add_empresa('Neoenergia');
SELECT add_empresa('ISA CTEEP');
SELECT add_empresa('Engie Brasil');
SELECT add_empresa('Taesa');
SELECT add_empresa('Sabesp');
SELECT add_empresa('Renaova');
SELECT add_empresa('Ger Paranapanema');
SELECT add_empresa('CESP');
SELECT add_empresa('Cemig');
SELECT add_empresa('Afluente T');