CREATE SEQUENCE empresa_id_seq START 1;

CREATE OR REPLACE FUNCTION add_empresa(nome_empresa VARCHAR(500))
    RETURNS INT AS
$$
DECLARE
    id_seq_em INT;
BEGIN
    id_seq_em = nextval('empresa_id_seq');

    INSERT INTO empresa (nome, cnpj)
    VALUES(nome_empresa, id_seq_em);

    RETURN id_seq_em + 1;
END;
$$ LANGUAGE plpgsql;

SELECT add_empresa('Simpar');
SELECT add_empresa('Cury');
SELECT add_empresa('Plano & Plano');
SELECT add_empresa('Petz');
SELECT add_empresa('Pague Menos');
SELECT add_empresa('Lavvi Incorporadora');
SELECT add_empresa('Quero-Quero');
SELECT add_empresa('d1000');
SELECT add_empresa('Grupo Soma');
SELECT add_empresa('Riva 9');
SELECT add_empresa('Ambipar');
SELECT add_empresa('Allpark');
SELECT add_empresa('Mitre Realty');
SELECT add_empresa('Moura Dubeux');
SELECT add_empresa('Bardella');
SELECT add_empresa('UPS');
SELECT add_empresa('Lockheed');
SELECT add_empresa('Johnson');
SELECT add_empresa('Fedex Corp');
SELECT add_empresa('Exxon Mobile');
SELECT add_empresa('Cophillips');
SELECT add_empresa('Caterpillar');
SELECT add_empresa('Bristolmyers');
SELECT add_empresa('Boeing');
SELECT add_empresa('Arcelor');
SELECT add_empresa('American Express');
SELECT add_empresa('Abbott Laboratories');
SELECT add_empresa('Santos - Brasil');
SELECT add_empresa('Randon Part');
SELECT add_empresa('Engie');
SELECT add_empresa('Lupatech');
SELECT add_empresa('Inepar');
SELECT add_empresa('Fras-Le');
SELECT add_empresa('Schulz');
SELECT add_empresa('Taurus Armas');
SELECT add_empresa('Whirlpool');
SELECT add_empresa('Ourofino S/A');
SELECT add_empresa('GOL');
SELECT add_empresa('Eternit');
SELECT add_empresa('Valid');
SELECT add_empresa('Triunfo Part');
SELECT add_empresa('PBG');
SELECT add_empresa('Marcopolo');
SELECT add_empresa('Cosan Log');
SELECT add_empresa('Aço Altona');
SELECT add_empresa('Eneva');
SELECT add_empresa('Weg');
SELECT add_empresa('ViaVarejo');
SELECT add_empresa('RUMO LOG');
SELECT add_empresa('Vale');
SELECT add_empresa('Usiminas');
SELECT add_empresa('Santos Brasil Participações');
SELECT add_empresa('Invepar');
SELECT add_empresa('Contax');
SELECT add_empresa('Celulose Irani');
SELECT add_empresa('CCR');
SELECT add_empresa('Cedro');
SELECT add_empresa('Netflix');
SELECT add_empresa('Nike');
SELECT add_empresa('MC Donald''s');
SELECT add_empresa('Home Depot');
SELECT add_empresa('Ford Motors');
SELECT add_empresa('Comcast');
SELECT add_empresa('Amazon');
SELECT add_empresa('Rodobens');
SELECT add_empresa('Saraiva Livr');
SELECT add_empresa('Rossi Resid');
SELECT add_empresa('Mundial');
SELECT add_empresa('Metal Leve');
SELECT add_empresa('Karsten');
SELECT add_empresa('Iochpe-Maxion');
SELECT add_empresa('Grendene');
SELECT add_empresa('Locamerica');
SELECT add_empresa('C&A');
SELECT add_empresa('Le Lis Blanc');
SELECT add_empresa('Grazziotin');
SELECT add_empresa('Estrela');
SELECT add_empresa('Direcional');
SELECT add_empresa('Coteminas');
SELECT add_empresa('Anima');
SELECT add_empresa('Even');
SELECT add_empresa('Marisa');
SELECT add_empresa('Movida');
SELECT add_empresa('JHSF');
SELECT add_empresa('Helbor');
SELECT add_empresa('PDG Realty');
SELECT add_empresa('Arezzo');
SELECT add_empresa('Ez Tec');
SELECT add_empresa('Cia Hering');
SELECT add_empresa('Alpargatas');
SELECT add_empresa('Smiles');
SELECT add_empresa('Localiza');
SELECT add_empresa('MRV Engenharia');
SELECT add_empresa('Magazine Luiza');
SELECT add_empresa('Lojas Renner');
SELECT add_empresa('Cogna');
SELECT add_empresa('Whirpool');
SELECT add_empresa('Via Varejo');
SELECT add_empresa('Tecnisa');
SELECT add_empresa('Starbuc');
SELECT add_empresa('Ser Educacional');
SELECT add_empresa('Saraiva livr');
SELECT add_empresa('Lojas Americanas');
SELECT add_empresa('Hoteis Othon');
SELECT add_empresa('Gafisa');
SELECT add_empresa('YDUQS');
SELECT add_empresa('Cyrela Realty');
SELECT add_empresa('CVC');
SELECT add_empresa('Walmart');
SELECT add_empresa('Starbucks');
SELECT add_empresa('Procter Gamble');
SELECT add_empresa('Pepsico Inc');
SELECT add_empresa('Colgate');
SELECT add_empresa('Coca-Cola');
SELECT add_empresa('Avon');
SELECT add_empresa('São Martinho');
SELECT add_empresa('MDiasBranco');
SELECT add_empresa('CAMIL');
SELECT add_empresa('Brasilagro');
SELECT add_empresa('Biosev');
SELECT add_empresa('Minerva');
SELECT add_empresa('Vivara');
SELECT add_empresa('Carrefour');
SELECT add_empresa('Pão de Açúcar');
SELECT add_empresa('Natura');
SELECT add_empresa('Marfrig');
SELECT add_empresa('JBS');
SELECT add_empresa('Proctor Gamble');
SELECT add_empresa('BRF');
SELECT add_empresa('BRB Banco');
SELECT add_empresa('Battistella');
SELECT add_empresa('Banpara');
SELECT add_empresa('Wells Fargo');
SELECT add_empresa('Visa');
SELECT add_empresa('Morgan Stanley');
SELECT add_empresa('Mastercard');
SELECT add_empresa('JPMorgan');
SELECT add_empresa('Honeywell');
SELECT add_empresa('GE');
SELECT add_empresa('Goldman Sachs');
SELECT add_empresa('Citigroup');
SELECT add_empresa('Bank America');
SELECT add_empresa('Sao Carlos');
SELECT add_empresa('LPS Brasil');
SELECT add_empresa('BMG');
SELECT add_empresa('Gradiente');
SELECT add_empresa('General Shopping');
SELECT add_empresa('Porto Seguro');
SELECT add_empresa('CSU CardSyst');
SELECT add_empresa('Brasil Brokers');
SELECT add_empresa('BR Properties');
SELECT add_empresa('Banrisul');
SELECT add_empresa('Banco Inter');
SELECT add_empresa('Santander BR');
SELECT add_empresa('Multiplan');
SELECT add_empresa('Itaú Unibanco');
SELECT add_empresa('Aliansce Sonae');
SELECT add_empresa('Banco Mercantil de Investimentos');
SELECT add_empresa('Mercantil do Brasil Financeira');
SELECT add_empresa('Log');
SELECT add_empresa('Itaúsa');
SELECT add_empresa('IRB Brasil RE');
SELECT add_empresa('Iguatemi');
SELECT add_empresa('Bradesco');
SELECT add_empresa('brMalls');
SELECT add_empresa('Alper');
SELECT add_empresa('BB Seguridade');
SELECT add_empresa('Banco Pan');
SELECT add_empresa('Banco do Brasil');
SELECT add_empresa('American Expre');
SELECT add_empresa('Celul Irani');
SELECT add_empresa('Freeport');
SELECT add_empresa('Paranapanema');
SELECT add_empresa('Ferbasa');
SELECT add_empresa('Eucatex');
SELECT add_empresa('Suzano Papel');
SELECT add_empresa('Klabin S/A');
SELECT add_empresa('Unipar');
SELECT add_empresa('Suzano Holding');
SELECT add_empresa('MMX Mineração');
SELECT add_empresa('Gerdau');
SELECT add_empresa('CSN');
SELECT add_empresa('Braskem');
SELECT add_empresa('3M');
SELECT add_empresa('Bradespar');
SELECT add_empresa('Arcel');
SELECT add_empresa('Zoetis Inc');
SELECT add_empresa('Zionsbancorp');
SELECT add_empresa('Zimmer Biome');
SELECT add_empresa('Yum Brands');
SELECT add_empresa('Dentsply Sir');
SELECT add_empresa('Xylem Inc');
SELECT add_empresa('Xilinx Inc');
SELECT add_empresa('Xcel Energy');
SELECT add_empresa('Westernunion');
SELECT add_empresa('Walgreens');
SELECT add_empresa('Waters Corp');
SELECT add_empresa('Western Bcor');
SELECT add_empresa('Wynn Resorts');
SELECT add_empresa('Weyerhaeuser');
SELECT add_empresa('Westrock Co');
SELECT add_empresa('Waste Manag');
SELECT add_empresa('Williams Cos');
SELECT add_empresa('Willis Tower');
SELECT add_empresa('Whirlpool Co');
SELECT add_empresa('Welltower In');
SELECT add_empresa('Wec Energy G');
SELECT add_empresa('Western Dig');
SELECT add_empresa('Workday Inc');
SELECT add_empresa('Wabtec Corp');
SELECT add_empresa('Vertex Pharm');
SELECT add_empresa('Verisign Inc');
SELECT add_empresa('Valley Ntion');
SELECT add_empresa('Valero Ener');
SELECT add_empresa('Vf Corp');
SELECT add_empresa('Ventas Inc');
SELECT add_empresa('Verisk Analy');
SELECT add_empresa('Vornado Real');
SELECT add_empresa('Vulcan Mater');
SELECT add_empresa('Varian Medic');
SELECT add_empresa('Us Steel');
SELECT add_empresa('Us Bancorp');
SELECT add_empresa('Unionpacific');
SELECT add_empresa('Unitedhealth');
SELECT add_empresa('Unilever');
SELECT add_empresa('Ubs Group');
SELECT add_empresa('United Renta');
SELECT add_empresa('Unum Group');
SELECT add_empresa('Ulta Beauty');
SELECT add_empresa('Universal He');
SELECT add_empresa('Udr Inc');
SELECT add_empresa('Uber Tech In');
SELECT add_empresa('United Airli');
SELECT add_empresa('Under Armour');
SELECT add_empresa('Terniumsa');
SELECT add_empresa('Twitter');
SELECT add_empresa('Tyson Foods');
SELECT add_empresa('Schlumberger');
SELECT add_empresa('Halliburton');
SELECT add_empresa('Chevron');
SELECT add_empresa('PETRORIO');
SELECT add_empresa('OSX Brasil');
SELECT add_empresa('Dommo');
SELECT add_empresa('Pet Manguinhos');
SELECT add_empresa('Ultrapar');
SELECT add_empresa('Petrobras');
SELECT add_empresa('Petrobras Distribuidora');
SELECT add_empresa('Exxon Mob');
SELECT add_empresa('Enauta Part');
SELECT add_empresa('Instituto Hermes Pardini SA');
SELECT add_empresa('Biomm');
SELECT add_empresa('Baumer');
SELECT add_empresa('Pfizer');
SELECT add_empresa('Merck');
SELECT add_empresa('Biotoscana');
SELECT add_empresa('Dimed');
SELECT add_empresa('Alliar');
SELECT add_empresa('OdontoPrev');
SELECT add_empresa('RD');
SELECT add_empresa('Qualicorp');
SELECT add_empresa('Johns');
SELECT add_empresa('Hypera Pharma');
SELECT add_empresa('Fleury');
SELECT add_empresa('Bristolmye');
SELECT add_empresa('Abbott Laboratori');
SELECT add_empresa('Locaweb');
SELECT add_empresa('Totvs');
SELECT add_empresa('Xerox');
SELECT add_empresa('Qualcomm');
SELECT add_empresa('Oracle');
SELECT add_empresa('Microsoft');
SELECT add_empresa('IBM');
SELECT add_empresa('Intel');
SELECT add_empresa('HP Company');
SELECT add_empresa('eBay');
SELECT add_empresa('Cisco');
SELECT add_empresa('Apple');
SELECT add_empresa('Linx');
SELECT add_empresa('Positivo Inf');
SELECT add_empresa('Ebay');
SELECT add_empresa('Verizon');
SELECT add_empresa('OI');
SELECT add_empresa('Tim Participações');
SELECT add_empresa('Telefônica Brasil S.A');
SELECT add_empresa('Telebras');
SELECT add_empresa('Att Inc');
SELECT add_empresa('Celpe');
SELECT add_empresa('CEEE-D');
SELECT add_empresa('Ceee-gt');
SELECT add_empresa('Casan');
SELECT add_empresa('CEG');
SELECT add_empresa('CEB');
SELECT add_empresa('Renova');
SELECT add_empresa('Coelce');
SELECT add_empresa('Celesc');
SELECT add_empresa('Alupar Investimento');
SELECT add_empresa('Sanepar');
SELECT add_empresa('CPFL Renovav');
SELECT add_empresa('Copel');
SELECT add_empresa('CPFL Energia');
SELECT add_empresa('Comgás');
SELECT add_empresa('AES Tietê');
SELECT add_empresa('Neoenergia');
SELECT add_empresa('ISA CTEEP');
SELECT add_empresa('Engie Brasil');
SELECT add_empresa('Taesa');
SELECT add_empresa('Sabesp');
SELECT add_empresa('Renaova');
SELECT add_empresa('Ger Paranapanema');
SELECT add_empresa('CESP');
SELECT add_empresa('Cemig');
SELECT add_empresa('Afluente T');
SELECT add_empresa('BTG Pactual Fundo de Fundos');
SELECT add_empresa('Bradesco Carteira Imobiliária Ativa');
SELECT add_empresa('Brasil Plural Absoluto Fundo de Fundos');
SELECT add_empresa('Capitania Reit FoF');
SELECT add_empresa('Caixa Rio Bravo II');
SELECT add_empresa('Caixa Rio Bravo');
SELECT add_empresa('Hedge Top FOFII 3');
SELECT add_empresa('CSHG Imobiliário FOF');
SELECT add_empresa('Mogno Fundo de Fundos');
SELECT add_empresa('Ourinvest Fundo de Fundos');
SELECT add_empresa('Rio Bravo IFIX');
SELECT add_empresa('RBR Alpha Fundo de Fundos');
SELECT add_empresa('Brasil Varejo');
SELECT add_empresa('Grand Plaza Shopping');
SELECT add_empresa('Hedge Atrium Shopping Santo André');
SELECT add_empresa('BTG Pactual Shoppings');
SELECT add_empresa('Eldorado');
SELECT add_empresa('General Shopping Ativo e Renda');
SELECT add_empresa('Vida Nova');
SELECT add_empresa('Floripa Shopping');
SELECT add_empresa('Via Parque Shopping');
SELECT add_empresa('General Shopping e Outlets do Brasil');
SELECT add_empresa('CSHG Brasil Shopping');
SELECT add_empresa('Hedge Shopping Praça da Moça');
SELECT add_empresa('Hedge Shopping Parque Dom Pedro');
SELECT add_empresa('Shopping Jardim Sul');
SELECT add_empresa('Parque Dom Pedro Shopping Center');
SELECT add_empresa('Multi Properties');
SELECT add_empresa('RB Capital General Shopping Sulacap');
SELECT add_empresa('Shopping Parque Dom Pedro');
SELECT add_empresa('Multi Shoppings');
SELECT add_empresa('Shopping Patio Higienopolis');
SELECT add_empresa('SPA Fundo de Investimento Imobiliário');
SELECT add_empresa('Vinci Shopping Centers');
SELECT add_empresa('Polo Shopping Indaiatuba');
SELECT add_empresa('Votorantim Shopping');
SELECT add_empresa('Shopping West Plaza');
SELECT add_empresa('BR Hotéis');
SELECT add_empresa('Hotel Maxinvest');
SELECT add_empresa('XP Hotéis');
SELECT add_empresa('Hospital da Criança');
SELECT add_empresa('Hospital Unimed Sul Capixaba');
SELECT add_empresa('Hospital Nossa Senhora de Lourdes');
SELECT add_empresa('Novo Horizonte');
SELECT add_empresa('Alianza Trust Renda Imobiliária');
SELECT add_empresa('Kinea Renda Imobiliária');
SELECT add_empresa('Caixa TRX Logística Renda');
SELECT add_empresa('Industrial do Brasil');
SELECT add_empresa('GGR Covepi Renda');
SELECT add_empresa('CSHG GR Louveira');
SELECT add_empresa('CSHG Logística');
SELECT add_empresa('Newport Logística');
SELECT add_empresa('Ourinvest Logistica');
SELECT add_empresa('Prologis Brazil Logistics Venture');
SELECT add_empresa('SDI Logística Rio');
SELECT add_empresa('Vinci Logística');
SELECT add_empresa('Votorantim Logística');
SELECT add_empresa('XP Log');
SELECT add_empresa('Torre Almirante');
SELECT add_empresa('BB Progressivo');
SELECT add_empresa('BB Votorantim Cidade Jardim Continental Tower');
SELECT add_empresa('Brasilio Machado');
SELECT add_empresa('BM Brascan Lajes Corporativas');
SELECT add_empresa('BTG Pactual Corporate Office');
SELECT add_empresa('Castello Branco Office Park');
SELECT add_empresa('Cyrela Commercial Properties');
SELECT add_empresa('Reag Renda Imobiliária');
SELECT add_empresa('Multigestão Renda Comercial');
SELECT add_empresa('Edifício Ourinvest');
SELECT add_empresa('Edifício Galeria');
SELECT add_empresa('Europa 105');
SELECT add_empresa('Edifício Almirante Barroso');
SELECT add_empresa('Continental Square Faria Lima');
SELECT add_empresa('Memorial Office');
SELECT add_empresa('Projeto Agua Branca');
SELECT add_empresa('Pedra Negra Renda Imobiliária');
SELECT add_empresa('Green Towers');
SELECT add_empresa('Mercantil do Brasil');
SELECT add_empresa('Pátria Edifícios Corporativos');
SELECT add_empresa('RB Capital Office Income');
SELECT add_empresa('RBR Properties');
SELECT add_empresa('Rio Bravo Renda Corporativa');
SELECT add_empresa('Renda de Escritórios');
SELECT add_empresa('Rio Negro');
SELECT add_empresa('Sia Corporate');
SELECT add_empresa('SDI Properties');
SELECT add_empresa('São Fernando');
SELECT add_empresa('SP Downtown');
SELECT add_empresa('Cyrela Thera Corporate');
SELECT add_empresa('Torre Norte');
SELECT add_empresa('Vector Queluz Lajes Corporativas');
SELECT add_empresa('Vila Olímpia Corporate');
SELECT add_empresa('V2 Properties');
SELECT add_empresa('XP Corporate Macaé');
SELECT add_empresa('TRX Edifícios Corporativos');
SELECT add_empresa('Anhanguera Educacional');
SELECT add_empresa('General Severiano');
SELECT add_empresa('Rio Bravo Renda Educacional');
SELECT add_empresa('Hedge Realty Development');
SELECT add_empresa('JT Prev FII Desenvolvimento Habitacional');
SELECT add_empresa('Luggo');
SELECT add_empresa('Mérito Desenvolvimento Imobiliário');
SELECT add_empresa('Nova I');
SELECT add_empresa('Ouro Preto Desenvolvimento Imobiliário I');
SELECT add_empresa('Personale I');
SELECT add_empresa('JHSF Rio Bravo Fazenda Boa Vista Capital Protegido');
SELECT add_empresa('RB Capital Desenvolvimento Residencial II');
SELECT add_empresa('RBR Desenvolvimento');
SELECT add_empresa('Grupo RCFA');
SELECT add_empresa('RB Capital Desenvolvimento Residencial III');
SELECT add_empresa('TG Ativo Real');
SELECT add_empresa('Tourmalet II');
SELECT add_empresa('Tourmalet I');
SELECT add_empresa('BB Progressivo II');
SELECT add_empresa('BB Renda Corporativa');
SELECT add_empresa('Banrisul Novas Fronteiras');
SELECT add_empresa('Rio Bravo Renda Varejo');
SELECT add_empresa('Opportunity');
SELECT add_empresa('JS Real Estate Multigestão');
SELECT add_empresa('Quasar Agro');
SELECT add_empresa('Treecorp Real Estate');
SELECT add_empresa('Átrio Reit Recebíveis Imobiliários');
SELECT add_empresa('Barigui Rendimento Imobiliários I');
SELECT add_empresa('BB Recebíveis Imobiliários');
SELECT add_empresa('Banestes Recebíveis Imobiliários');
SELECT add_empresa('Inter Títulos Imobiliários');
SELECT add_empresa('BTG Pactual Crédito Imobiliário');
SELECT add_empresa('BTG Pactual Fundo de CRI');
SELECT add_empresa('São Domingos');
SELECT add_empresa('CSHG Recebíveis Imobiliários');
SELECT add_empresa('Iridium Recebíveis Imobiliários');
SELECT add_empresa('JPP Allocation Mogno');
SELECT add_empresa('Kinea Rendimentos Imobiliários');
SELECT add_empresa('Kinea Índice de Preços');
SELECT add_empresa('Mauá Capital Recebíveis Imobiliários');
SELECT add_empresa('NCH Brasil Recebíveis Imobiliários');
SELECT add_empresa('Polo Recebíveis Imobiliários I');
SELECT add_empresa('Polo Recebíveis Imobiliários II');
SELECT add_empresa('Rio Bravo Crédito Imobiliário I');
SELECT add_empresa('Rio Bravo Crédito Imobiliário IV');
SELECT add_empresa('RBR Rendimento High Grade');
SELECT add_empresa('RBR Private Crédito Imobiliário');
SELECT add_empresa('Rio Bravo Crédito Imobiliário II');
SELECT add_empresa('RB Capital Rendimentos');
SELECT add_empresa('BB Renda de Papeis Imobiliários II');
SELECT add_empresa('Socopa Fundo de Investimento Imobiliário');
SELECT add_empresa('BB Renda de Papéis Imobiliários');
SELECT add_empresa('Santander Papeis Imobiliários CDI');
SELECT add_empresa('UBS (BR) Recebíveis Imobiliários');
SELECT add_empresa('Valora RE III');
SELECT add_empresa('Votorantim Securities Master');
SELECT add_empresa('Fator Verita');
SELECT add_empresa('XP Crédito Imobiliário');
SELECT add_empresa('Áquilla');
SELECT add_empresa('FOF Integral Brei');
SELECT add_empresa('Kinea FII');
SELECT add_empresa('Max Retail');
SELECT add_empresa('RB Capital Renda II');
SELECT add_empresa('Ancar IC');
SELECT add_empresa('Diamante');
SELECT add_empresa('HSI Mall');
SELECT add_empresa('Malls Brasil Plural');
SELECT add_empresa('XP Malls FII');
SELECT add_empresa('Áquilla Renda');
SELECT add_empresa('RB Capital Renda I');
SELECT add_empresa('Infra Real State');
SELECT add_empresa('Vereda');
SELECT add_empresa('XP Industrial');
SELECT add_empresa('Yaguara Capital High Yield');
SELECT add_empresa('Caixa Cedae');
SELECT add_empresa('CSHG Real Estate');
SELECT add_empresa('Presidente Vargas');
SELECT add_empresa('Campus Faria Lima');
SELECT add_empresa('CSHG Renda Urbana');
SELECT add_empresa('JPP Capital');
SELECT add_empresa('Even Permuta Kinea');
SELECT add_empresa('Kiena II real Estate Equity');
SELECT add_empresa('Lateres');
SELECT add_empresa('Panamby');
SELECT add_empresa('RB Capital TFO Situs');
SELECT add_empresa('Santander Agências');
SELECT add_empresa('Brazil Realty');
SELECT add_empresa('Hectare CE FII');
SELECT add_empresa('Santander Renda de Alugueis');
SELECT add_empresa('Capitania Securities II');
SELECT add_empresa('Habitat II');
SELECT add_empresa('Habitat I');
SELECT add_empresa('Kinea High Yield CRI');
SELECT add_empresa('Maxi Renda');
SELECT add_empresa('Nestpar');
SELECT add_empresa('Ourinvest Cyrela');
SELECT add_empresa('Plural Recebíveis');
SELECT add_empresa('CSHG TOP FOFII 2');
SELECT add_empresa('CSHG TOP FOFII');
SELECT add_empresa('Ourinvest RE I');
SELECT add_empresa('FII BRLPROP');
SELECT add_empresa('LOGCP Inter');
SELECT add_empresa('VBI LOGÍSTICO');
SELECT add_empresa('SC 401');
SELECT add_empresa('VBI FL 4440');
SELECT add_empresa('CSHG Prime Offices');
SELECT add_empresa('The One');
SELECT add_empresa('TB Office');
SELECT add_empresa('Vinci Offices');
SELECT add_empresa('MAC FII');
SELECT add_empresa('LOFT I');
SELECT add_empresa('STARX FII');
SELECT add_empresa('UBS (BR) Office');
SELECT add_empresa('XP PROPERTIES');
SELECT add_empresa('VBI CRI');
SELECT add_empresa('OURINVEST JPP');
SELECT add_empresa('SCP');
SELECT add_empresa('EUROPAR');
SELECT add_empresa('HAZ');
SELECT add_empresa('CENESP');
SELECT add_empresa('DOVEL');